spring:
  application:
    name: security-security
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtProject # Укажите ваш URL БД
    driver-class-name: org.postgresql.Driver
    username: postgres                                 # Ваш username
    password: 31315                                  # Ваш пароль
  jpa:
    hibernate:
      ddl-auto: update                                       # Важно: не create-drop!
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect     # Правильный диалект
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855